name:                some-dict-of
version:             0.1.0.1
github:              "parsonsmatt/some-dict-of"
license:             BSD3
author:              "Matt Parsons"
maintainer:          "parsonsmatt@gmail.com"
copyright:           "Matt Parsons"

extra-source-files:
- README.md
- changelog.md

# Metadata used when publishing your package
synopsis:            Carry evidence of constraints around
category:            Constraints

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/parsonsmatt/some-dict-of#readme>

dependencies:
- base >= 4.10 && < 5
- constraints

library:
  source-dirs: src

tests:
  discover-instances-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - some-dict-of
